name: Black_and_test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Black_and_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      
    - uses: actions/setup-python@main
      name: Set up Python 3.8
      with:
        python-version: '3.8'
        architecture: 'x64'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest black>=22.3.0
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python -m pip install . 
    
    - uses: psf/black@stable
      name: Black Formatting
      with:
        options: "--check --diff --verbose"
        src: "."
        version: "22.3.0"
    
    - name: Run tests
      id: tests
      run: |
        pytest tests/